### ISSUE TITLE
Missing locale

### ISSUE THREAD

**Issue by thedayofcondor** [KudoAI/chatgpt.js#182]
Hi, 
the extension currently fails to run with a 404 error from `chatgpt.js` line 30
`Failed to load resource: the server responded with a status of 404 () https://raw.githubusercontent.com/KudoAI/chatgpt.js/main/data/_locales/en_GB/messages.json` does not exist

By the way - thank your work - I do not understand why OpenAI insists on a narrow chat window...

**Comment by Luwa-Tech** [comment]
Looks like `en_GB` folder does not exist. I assume creating it will fix the issue. @adamlui I would love to be assigned this issue if my proposed solution would fix it. thanks

**Comment by adamlui** [comment]
Yes @Luwa-Tech that would be great! Sorry @thedayofcondor most my day was tied up securing a second booster (I'm severely afflicted by long COVID since 2020 so need continuous shots) and then I got caught up with some other tasks, one note about the locales is not all browsers support the fetching due to CORS (I tested in Firefox it works well I think) but @Luwa-Tech your proposed fix would at least create the data first, then I need to fix the overall issue of bypassing CORS + logic to default to en if region data is not found

**Comment by thedayofcondor** [comment]
@adamlui ouch that sucks! Hope you will feel better soon!

**Comment by Luwa-Tech** [comment]
@adamlui Wishing you a quick recovery and a healthier life. okay.. I'm on it.

**Comment by adamlui** [comment]
I removed the message fetching for now until/if OpenAI relaxes their CSP
